name: Test and Build
on:
  push:
    branches: ["main"]
permissions:
  contents: read
jobs:
  test_and_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install Uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Verificar instalación
        run: uv --version
      - name: Instalar dependencias con Uv
        run: uv sync
      - name: Ejecutar script UV
        working-directory: src
        run: uv run pytest test.uv
